# Generated by Django 2.0.3 on 2018-03-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
